---
title: "appledore_presentationmap"
author: "Kate Sheridan"
date: "3/25/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(sf)
library(here)

#shapefile of appledore
load(here("data","shapes_to_plot","appledore.rds"))
```

palette is:
`#bcbcd2, #94b4d8, #5484c4, #374658, #a08b5a, #806238, #543414, #3a230e`
lavender grey, pale cerulean, glaucous, charcoal, metallic sunburst,
coyote brown, dark brown, bistre

sets of 2 should be primarily drawn from the middle two of each part of
the palette: 
two blues 
#94b4d8, #5484c4 
two browns 
#806238, #543414 
blue brown light 
#94b4d8,#806238 
blue brown dark 
#5484c4, #543414




```{r scratch using existing polygons}
# from split script

#polygons and cleanup
polys <- readRDS(here("data", "Appledore Polygons", "appledore_kml.rds")) 

#SE/SW overlap goes to SW
polys2 <- bind_rows(
  polys[2,] %>% st_make_valid(), 
  polys[1,] %>% st_make_valid(),
          st_difference(polys[3,], polys[4,]),
          st_difference(polys[4,], polys[2,])) %>%
  mutate(geometry = st_cast(geometry, "POLYGON")) %>%
  ungroup()
  
polys[c(2,4),]
polys[,2]
        
polys2 <- bind_rows(
  #polys[c(1,2,4),] %>% st_make_valid(),
  st_union(polys[c(2,4),], by_feature = FALSE),
  st_difference(polys[3,], polys[4,])
  ) %>%
  mutate(geometry = st_cast(geometry, "POLYGON"))

protected <- bind_rows(
  polys[c(2,4),] %>% st_make_valid()) %>%  
  mutate(geometry = st_cast(geometry, "POLYGON")) %>%
  st_union()


exposed <- bind_rows(
  polys[c(1,3),] %>% st_make_valid()) %>%  
  mutate(geometry = st_cast(geometry, "POLYGON")) %>%
  st_union()


#see how the polys lineup

# polygons for fill/exposed test


ggplot(appledore) +
#  geom_sf() +
  geom_sf(data = exposed, alpha = 0.8, fill = 'orange', col = NA) +
  geom_sf(data = protected, fill = 'blue', col = NA) +
  geom_sf() +
  theme(#axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = 'grey70'))
```



```{r figure}
#exposed polygon
exposed <- st_as_sfc(x = "POLYGON((-70.614 42.988, -70.615 42.992, -70.613 42.995, -70.608 42.995, -70.608 42.983, -70.611 42.983, -70.612 42.985, -70.614 42.988))",
                     crs = 4326)



#to-do notes: put an ellipse around island around to mask


# appledore sf, custom polygons
ggplot(appledore) +
  #geom_sf(data = protected, fill = 'blue', col = NA) +
  geom_sf(data = exposed, fill = '#94b4d8') + #fill behind exposed
  geom_sf(fill = 'grey88') +
  ylim(42.9845,42.993) +
  xlim(-70.619,-70.609) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = '#806238') #rect in backgorund represents protected
        )
```

